/* eslint-disable no-unused-vars */
const API_BASE_URL = 'http://localhost:8190/league';

const SEASONS_ENDPOINT = '/season';
const SEASON_DETAILS_ENDPOINT = '/details?seasonId=';

const TOURNAMENTS_ENDPOINT = '/tournament';
const TOURNAMENT_DETAILS_ENDPOINT = '/details?tournamentId=';
const TOURNAMENT_START_ENDPOINT = '/start';
const TOURNAMENT_ACTIVE_ENDPOINT = '/active';

const PLAYERS_ENDPOINT = '/player';
const PLAYER_DETAILS_ENDPOINT = '/details?playerId=';

export const SEASONS_API_URL = API_BASE_URL + SEASONS_ENDPOINT;
export const SEASONS_DETAILS_API_URL = API_BASE_URL + SEASONS_ENDPOINT + SEASON_DETAILS_ENDPOINT;

export const TOURNAMENTS_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT;
export const TOURNAMENT_DETAILS_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_DETAILS_ENDPOINT;
export const TOURNAMENT_START_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_START_ENDPOINT;
export const TOURNAMENT_ACTIVE_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_ACTIVE_ENDPOINT;

export const PLAYERS_API_URL = API_BASE_URL + PLAYERS_ENDPOINT;
export const PLAYER_DETAILS_API_URL = API_BASE_URL + PLAYERS_ENDPOINT + PLAYER_DETAILS_ENDPOINT;