/* eslint-disable no-unused-vars */
const API_BASE_URL = 'http://localhost:8190/league';

const LOGOUT_ENDPOINT = "/logout";

const AUTHORIZATION_ENDPOINT = "/authorization";
const AUTHORIZATION_REGISTER_ENDPOINT = "/register";
const AUTHORIZATION_AUTHENTICATE_ENDPOINT = "/authenticate";
const AUTHORIZATION_REFRESH_ENDPOINT = "/refresh";

const SEASONS_ENDPOINT = '/season';
const SEASON_DETAILS_ENDPOINT = '/details?seasonId=';

const TOURNAMENTS_ENDPOINT = '/tournament';
const TOURNAMENT_DETAILS_ENDPOINT = '/details?tournamentId=';
const TOURNAMENT_START_ENDPOINT = '/start';
const TOURNAMENT_ACTIVE_ENDPOINT = '/active';

const PLAYERS_ENDPOINT = '/player';
const PLAYER_DETAILS_ENDPOINT = '/details?playerId=';

export const LOGOUT_API_URL = API_BASE_URL + LOGOUT_ENDPOINT;

export const AUTHENTICATE_API_URL = API_BASE_URL + AUTHORIZATION_ENDPOINT + AUTHORIZATION_AUTHENTICATE_ENDPOINT;
export const REFRESH_API_URL = API_BASE_URL + AUTHORIZATION_ENDPOINT + AUTHORIZATION_REFRESH_ENDPOINT;

export const SEASONS_API_URL = API_BASE_URL + SEASONS_ENDPOINT;
export const SEASONS_DETAILS_API_URL = API_BASE_URL + SEASONS_ENDPOINT + SEASON_DETAILS_ENDPOINT;

export const TOURNAMENTS_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT;
export const TOURNAMENT_DETAILS_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_DETAILS_ENDPOINT;
export const TOURNAMENT_START_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_START_ENDPOINT;
export const TOURNAMENT_ACTIVE_API_URL = API_BASE_URL + TOURNAMENTS_ENDPOINT + TOURNAMENT_ACTIVE_ENDPOINT;

export const PLAYERS_API_URL = API_BASE_URL + PLAYERS_ENDPOINT;
export const PLAYER_DETAILS_API_URL = API_BASE_URL + PLAYERS_ENDPOINT + PLAYER_DETAILS_ENDPOINT;